Repository jenkinsci/ssh-agents-plugin, pull requests merged in 2019-10, with the labels that each got.

#153 [JENKINS-59728] Bump Jenkins core to 2.190.1
  Jenkinsfile
  pom.xml
Labels: breaking, dependencies

#155 chore: add .editorconfig configuration file
  .editorconfig
Labels: chore

#156 [1.30.x] Use ChannelBuilder instead of deprecated Channel constructor (#152)
  src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java
Labels: backport

#158 [ssh-slaves-2.0] [JENKINS-59728] Bump Jenkins core to 2.190.1 (#153)
  Jenkinsfile
  pom.xml
Labels: backport

#159 Fix "agent agents" terminology
  doc/CONFIGURE.md
  src/main/resources/hudson/plugins/sshslaves/Messages.properties
  src/main/resources/hudson/plugins/sshslaves/Messages_es.properties
Labels: bug

#160 [ssh-slaves-2.0] [JENKINS-42840] Slave to agent renaming (leftovers) (#151)
  src/main/resources/hudson/plugins/sshslaves/SSHConnector/config_zh_TW.properties
  src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help.properties
  src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help_de.properties
  src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly
  src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
  src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
Labels: backport

#161 [ssh-slaves-2.0] Replace usage of deprecated remoting Base64 class (#150)
  src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
Labels: backport

#162 [1.30.x] Fix "agent agents" terminology (#159)
  doc/CONFIGURE.md
  src/main/resources/hudson/plugins/sshslaves/Messages.properties
  src/main/resources/hudson/plugins/sshslaves/Messages_es.properties
Labels: backport

#163 [ssh-slaves-2.0] Fix "agent agents" terminology (#159)
  doc/CONFIGURE.md
  src/main/resources/hudson/plugins/sshslaves/Messages.properties
  src/main/resources/hudson/plugins/sshslaves/Messages_es.properties
Labels: backport

#143 [JENKINS-58589] Re-make the retry connection process
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
  src/main/resources/hudson/plugins/sshslaves/Messages.properties
  src/main/resources/hudson/plugins/sshslaves/Messages_es.properties
  src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
Labels: bug

#164 [JENKINS-59763] Remove SFTPClient
  src/main/java/com/trilead/ssh2/jenkins/SFTPClient.java
Labels: deprecated

#166 [JENKINS-53720] JDK11 Build Flow: FindBugs fails with RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE in some classes
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Labels: chore

#167 [JENKINS-45001] KnownHostsFileKeyVerificationStrategy is not configuable
  doc/CONFIGURE.md
  src/main/java/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy.java
  src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
Labels: enhancement
