Repository jenkinsci/ssh-agents-plugin, pull requests merged in 2019-07, with the labels that each got.

#136 [JENKINS-58340] docker-plugin-1.1.6 docker cloud does not work with >=ssh-slaves-plugin-1.30.0
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Labels: bug

#138 docs: add instructions to use workdir in a no C drive
  doc/TROUBLESHOOTING.md
Labels: docs

#139 [JENKINS-56187] manually provided key verification strategy crashes
  src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
  src/main/resources/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy/config.jelly
Labels: bug

#141 [JENKINS-54897] block connection when a connection exists
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
  src/main/resources/hudson/plugins/sshslaves/Messages.properties
Labels: bug

#142 [JENKINS-58588] do not remove remoting.jar on disconnection
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Labels: enhancement

#140 [JENKINS-44111] add also jar cache dir parameter
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
  src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-workDir.html
  src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
Labels: bug

#144 Enable Release Drafter for the repository
  .github/release-drafter.yml
Labels: internal

#145 Move Changelog to GitHub Releases
  CHANGELOG.md
  README.md
Labels: documentation
