Repository jenkinsci/ssh-agents-plugin, pull requests merged in 2020-01, with the labels that each got.

#168 [JENKINS-47510] RemoteLauncher.isUnix() is not overridden - always returns master OS
  src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java
Labels: bug

#171 [JENKINS-42840] - Cleanup the "slave" mention leftovers in the documentation
  CHANGELOG.md
  doc/CONFIGURE.md
  src/main/java/hudson/plugins/sshslaves/PluginImpl.java
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
  src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
  src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
  src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
Labels: documentation

#172 Update the changelog badge title to make the purpose more explicit
  README.md
Labels: documentation

#173 Bump jcasc version
  pom.xml
Labels: dependencies

#176 [JENKINS-60827] - Move the Cygwin Wiki pages to GitHub, update the terminology
  README.md
  doc/CYGWIN.md
Labels: documentation

#175 [1.30.x] Bump jcasc version (#173)
  pom.xml
Labels: backport
