Repository jenkinsci/ssh-agents-plugin, pull requests merged in 2020-04, with the labels that each got.

#179 Deleting obsolete RemoteLauncher
  src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java
Labels: chore

#178 cleanupConnection should not block on Connection.close
  src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Labels: bug

#181 docs: note about supported key formats
  doc/CONFIGURE.md
Labels: docs

#182 docs: add also a troubleshooting section
  doc/TROUBLESHOOTING.md
Labels: docs
