Repository jenkinsci/ssh-agents-plugin, pull requests merged in 2023-12, with the labels that each got.

#456 Removing `Retry`
  src/test/java/hudson/plugins/sshslaves/agents/AgentConnectionBase.java
  src/test/java/hudson/plugins/sshslaves/rules/Retry.java
Labels: developer

#461 Use `@ClassRule` for checking platform details
  src/test/java/hudson/plugins/sshslaves/agents/AgentConnectionBase.java
Labels: developer

#458 Enable Docker-based tests
  Jenkinsfile
Labels: developer

#462 Replace outdated terminology
  .github/CODEOWNERS
  CHANGELOG.md
  README.md
  doc/TROUBLESHOOTING.md
  pom.xml
Labels: enhancement

#463 Remove PR template in favor of org-level templates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore
